server:
  port: 8280
  servlet:
    context-path: /backend

spring:
  datasource:
    url: jdbc:h2:mem:my-database;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
    console.path: /h2-console
    console.settings.trace: false
    spring:
      h2:
        console:
          settings:
            web-allow-others: false

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect